# Generated by Django 3.1.6 on 2021-02-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrationsp',
            new_name='registrations',
        ),
    ]
